/**
 * Model Registry - Auto-generated from shared/model_registry.json
 * DO NOT EDIT THIS FILE MANUALLY!
 *
 * To add a new model:
 * 1. Edit shared/model_registry.json
 * 2. Run: npm run generate-config (or it runs automatically on build)
 *
 * Generated: 2025-11-07T04:09:43.892Z
 */

export const MODELS = {
  "nova_pro": {
    "id": "nova_pro",
    "label": "Amazon Nova Pro",
    "description": "Fast and cost-effective model for most research tasks",
    "bedrock_id": "us.amazon.nova-pro-v1:0",
    "provider": "amazon",
    "category": "general",
    "recommended_for": [
      "chat",
      "research"
    ]
  },
  "claude_sonnet45": {
    "id": "claude_sonnet45",
    "label": "Claude Sonnet 4.5",
    "description": "Most capable model with superior reasoning and analysis",
    "bedrock_id": "us.anthropic.claude-sonnet-4-5-20250929-v1:0",
    "provider": "anthropic",
    "category": "premium",
    "recommended_for": [
      "research",
      "chat"
    ]
  },
  "claude_haiku45": {
    "id": "claude_haiku45",
    "label": "Claude Haiku 4.5",
    "description": "Fastest and most cost-effective Claude model",
    "bedrock_id": "us.anthropic.claude-haiku-4-5-20251001-v1:0",
    "provider": "anthropic",
    "category": "fast",
    "recommended_for": [
      "chat",
      "research"
    ]
  },
  "qwen3_mixed": {
    "id": "qwen3_mixed",
    "label": "Qwen3",
    "description": "Mix of Qwen3-32B and Qwen3-235B optimized by task complexity",
    "bedrock_id": "qwen.qwen3-32b-v1:0",
    "provider": "qwen",
    "category": "general",
    "recommended_for": [
      "research"
    ]
  },
  "llama_maverick": {
    "id": "llama_maverick",
    "label": "Llama Maverick",
    "description": "Open source model for research tasks",
    "bedrock_id": "us.meta.llama4-maverick-17b-instruct-v1:0",
    "provider": "meta",
    "category": "open-source",
    "recommended_for": [
      "research"
    ]
  }
};

export const ALIASES = {
  "claude_haiku": "claude_haiku45",
  "claude_sonnet": "claude_sonnet45",
  "haiku45": "claude_haiku45",
  "sonnet45": "claude_sonnet45"
};

/**
 * Get model info by ID (resolves aliases)
 */
export function getModel(modelId) {
  const resolvedId = ALIASES[modelId] || modelId;
  return MODELS[resolvedId];
}

/**
 * Get list of models for dropdown (filtered by usage)
 */
export function getModelOptions(recommendedFor = null) {
  let models = Object.values(MODELS);

  if (recommendedFor) {
    models = models.filter(m => m.recommended_for && m.recommended_for.includes(recommendedFor));
  }

  return models.map(m => ({
    value: m.id,
    label: m.label,
    description: m.description
  }));
}

/**
 * Format model ID to display name
 */
export function formatModelName(modelId) {
  const model = getModel(modelId);
  return model ? model.label : modelId;
}

// Legacy exports for backward compatibility
export const LLM_MODELS = getModelOptions('research');
export const CHAT_MODELS = getModelOptions('chat');
